"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#### BASE_DIR: project 절대경로.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$)lo+r0y+8$igkaoku#=1%)-024q+an_b9@_v4-$zzf^nmpm^8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
    'account',
    'django_bootstrap5'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # app들/templates 이외 template저장 디렉토리 경로 지정.
        'APP_DIRS': True, # app/templates 디렉토리를 자동으로 templates 저장경로로 인식.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'
# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


################################
# User model 등록
################################
AUTH_USER_MODEL = "account.User"  # AbstractUser 클래스 이름.

###############################
# 로그인 관련 설정
###############################
LOGIN_URL = '/account/login' # 로그인 안한 사용자가 @login_required View를 호출했을 때 이동.
LOGIN_REDIRECT_URL = '/' # LoginView 사용시 로그인 성공후 이동할 페이지
LOGOUT_REDIRECT_URL = '/'# LogoutView 사용시 로그아웃 처리후 이동할 페이지.

##############################
# MEDIA 설정 - 파일업로드 설정
##############################
MEDIA_ROOT = BASE_DIR / 'media' # 업로드 파일 저장할 경로.
MEDIA_URL = '/media/'  # 업로드된 파일을 요청할 때 사용할 url

################################################
# static 파일 설정 (js, css, image 파일들)
#  1. app/static  아래 저장된 파일들은 자동으로 인식(개발서버-runserver)
#  1이외 경로의 static 파일 settings.py에 등록
################################################
STATIC_URL = '/static/'  # 정적 파일들을 클라이어트가 요청할 때 사용할 시작 url
STATICFILES_DIRS =[BASE_DIR / "static_files",] # app/static 이외의 경로 설정.
STATIC_ROOT = BASE_DIR / 'static'
# app 별로 나눠져 있는 static 파일들을 모아놓으 디렉토리. (배포할 때 필요)
## python  manage.py  collectstatic